name: Build

on:
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/*testing/**'
      - '!projects/demo/**'
      - '!projects/icons/src/**'
      - '**/build.yml'
      - 'angular.json'
      - 'package.json'
      - 'tsconfig*'
    branches:
      - main
      - '!release/**'
  push:
    branches:
      - main
      - '!release/**'
env:
  NX_BRANCH: ${{ github.event.number }}
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build:
    name: Packages
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run affected builds for libraries based on main branch
        if: ${{ env.IS_MAIN_BRANCH == 'false' }}
        run: |
          npm run affected:build:libs
          npm run exec ./scripts/check-dist.ts

      - name: Run all builds for libraries only in main branch
        if: ${{ env.IS_MAIN_BRANCH == 'true' }}
        run: npm run run-many:build:libs

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
