name: Unit tests

on:
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/*testing/**'
      - '!projects/demo/**'
      - '!projects/icons/**'
      - '**/test.yml'
      - 'angular.json'
      - 'package.json'
      - 'karma.conf.js'
      - 'karma.config.js'
      - 'tsconfig*'
  push:
    branches:
      - main
      - '!release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  test:
    name: Karma
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run all tests for get coverage (with nx cache)
        run: npm run run-many:test:libs

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/kit/
          flags: summary,kit
          name: kit
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/core/
          flags: summary,core
          name: core
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/cdk/
          flags: summary,cdk
          name: cdk
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-tablebars/
          flags: summary,addon-tablebars
          name: addon-tablebars
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-table/
          flags: summary,addon-table
          name: addon-table
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-mobile/
          flags: summary,addon-mobile
          name: addon-mobile
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-editor/
          flags: summary,addon-editor
          name: addon-editor
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-doc/
          flags: summary,addon-doc
          name: addon-doc
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-commerce/
          flags: summary,addon-charts
          name: addon-commerce
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-charts/
          flags: summary,addon-charts
          name: addon-charts

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
